use_frameworks!

platform :ios, '9.0'

target 'publicSDKTest_Example' do
  pod 'publicSDKTest', :path => '../'

  target 'publicSDKTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
